name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci --ignore-scripts
    - run: echo "$PWD/node_modules/.bin" >> "$GITHUB_PATH"
    - run: deno cache src/cli.ts
    - run: deno lint
    - run: deno fmt --check
    - run: npm run build
    - run: lib/cli.js --outDir nodejs/
    - run: git diff --no-index lib/ nodejs/
