name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: denolib/setup-deno@v2
    - uses: actions/checkout@v2
    - run: npm ci --ignore-scripts
    - run: npm run prepare
    - run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - run: npm publish --ignore-scripts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
