name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: notiz-dev/github-action-json-property@v0.1.0
      with:
        path: package.json
        prop_path: engines.deno
      id: version
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ steps.version.outputs.prop }}
    - run: npm ci --ignore-scripts
    - run: npm run prepare
    - run: npm publish --ignore-scripts
      env:
        npm_config__auth: ${{ secrets.NPM_TOKEN }}
